substitutions:
  device_name: wooxr4785
  friendly_name: wooxr4785  

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp01_1m

logger:

api:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    id: "${device_name}_button"
    on_press:
      - switch.toggle: "${device_name}_relay"


switch:
  - platform: gpio
    name: "${friendly_name}"
    id: "${device_name}_relay"
    pin: GPIO05
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led
    restore_mode: ALWAYS_ON
    
output:
  - platform: gpio
    pin: GPIO04
    inverted: true
    id: led

sensor:
  - <<: !include includes/sensors/uptime.yaml
  - <<: !include includes/sensors/wifi_signal.yaml

text_sensor:
  - <<: !include includes/text_sensor/version.yaml
  - <<: !include includes/text_sensor/wifi_info.yaml
      
<<: !include includes/default.yaml
      
